# Generated by Django 5.0.14 on 2025-06-16 07:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0004_delete_fiscalperiodfilter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glpost',
            fields=[
                ('acctid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ACCTID', max_length=45, primary_key=True, serialize=False)),
                ('fiscalyr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FISCALYR', max_length=4)),
                ('fiscalperd', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FISCALPERD', max_length=2)),
                ('srcecurn', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SRCECURN', max_length=3)),
                ('srceledger', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SRCELEDGER', max_length=2)),
                ('srcetype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SRCETYPE', max_length=2)),
                ('postingseq', models.DecimalField(db_column='POSTINGSEQ', decimal_places=0, max_digits=7)),
                ('cntdetail', models.DecimalField(db_column='CNTDETAIL', decimal_places=0, max_digits=7)),
                ('audtdate', models.DecimalField(db_column='AUDTDATE', decimal_places=0, max_digits=9)),
                ('audttime', models.DecimalField(db_column='AUDTTIME', decimal_places=0, max_digits=9)),
                ('audtuser', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AUDTUSER', max_length=8)),
                ('audtorg', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AUDTORG', max_length=6)),
                ('jrnldate', models.DecimalField(db_column='JRNLDATE', decimal_places=0, max_digits=9)),
                ('batchnbr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BATCHNBR', max_length=6)),
                ('entrynbr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ENTRYNBR', max_length=5)),
                ('transnbr', models.DecimalField(db_column='TRANSNBR', decimal_places=0, max_digits=7)),
                ('editallowd', models.SmallIntegerField(db_column='EDITALLOWD')),
                ('consolidat', models.SmallIntegerField(db_column='CONSOLIDAT')),
                ('companyid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='COMPANYID', max_length=8)),
                ('jnldtldesc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='JNLDTLDESC', max_length=60)),
                ('jnldtlref', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='JNLDTLREF', max_length=60)),
                ('transamt', models.DecimalField(db_column='TRANSAMT', decimal_places=3, max_digits=19)),
                ('transqty', models.DecimalField(db_column='TRANSQTY', decimal_places=3, max_digits=19)),
                ('scurndec', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SCURNDEC', max_length=1)),
                ('scurnamt', models.DecimalField(db_column='SCURNAMT', decimal_places=3, max_digits=19)),
                ('hcurncode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HCURNCODE', max_length=3)),
                ('ratetype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RATETYPE', max_length=2)),
                ('scurncode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SCURNCODE', max_length=3)),
                ('ratedate', models.DecimalField(db_column='RATEDATE', decimal_places=0, max_digits=9)),
                ('convrate', models.DecimalField(db_column='CONVRATE', decimal_places=7, max_digits=15)),
                ('ratespread', models.DecimalField(db_column='RATESPREAD', decimal_places=7, max_digits=15)),
                ('datemtchcd', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DATEMTCHCD', max_length=1)),
                ('rateoper', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RATEOPER', max_length=1)),
                ('drilsrcty', models.SmallIntegerField(db_column='DRILSRCTY')),
                ('drilldwnlk', models.DecimalField(db_column='DRILLDWNLK', decimal_places=0, max_digits=19)),
                ('drilapp', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DRILAPP', max_length=2)),
                ('rptamt', models.DecimalField(db_column='RPTAMT', decimal_places=3, max_digits=19)),
                ('values', models.IntegerField(db_column='VALUES')),
                ('docdate', models.DecimalField(db_column='DOCDATE', decimal_places=0, max_digits=9)),
                ('txrptstat', models.IntegerField(db_column='TXRPTSTAT')),
                ('taxauth', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TAXAUTH', max_length=12)),
                ('txaccttype', models.SmallIntegerField(db_column='TXACCTTYPE')),
            ],
            options={
                'db_table': 'glpost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('batchnbr', models.CharField(default='004568', max_length=6)),
                ('entrynbr', models.CharField(default='00001', max_length=5)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('supporting_docs_id', models.AutoField(primary_key=True, serialize=False)),
                ('batchnbr', models.CharField(default='004568', max_length=6)),
                ('entrynbr', models.CharField(default='00001', max_length=5)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('fiscal_period', models.CharField(max_length=2)),
                ('supported', models.BooleanField(default=False)),
                ('transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('support_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocumentFile',
            fields=[
                ('doc_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'png'])])),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transactions.supportingdocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['project', 'fiscal_year', 'fiscal_period'], name='transaction_project_484e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['supported'], name='transaction_support_995c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['batchnbr', 'entrynbr'], name='transaction_batchnb_977e2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supportingdocument',
            unique_together={('project', 'batchnbr', 'entrynbr', 'fiscal_year', 'fiscal_period')},
        ),
    ]
