# Generated by Django 5.0.14 on 2025-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='entrynbr',
            field=models.CharField(default='00002', max_length=5),
        ),
    ]
