# Generated by Django 5.0.14 on 2025-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_comments_entrynbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eneba',
            fields=[
                ('cntbtch', models.IntegerField(db_column='CNTBTCH', primary_key=True, serialize=False)),
                ('cntitem', models.IntegerField(db_column='CNTITEM')),
                ('docline', models.IntegerField(db_column='DOCLINE')),
                ('audtdate', models.DecimalField(db_column='AUDTDATE', decimal_places=0, max_digits=9)),
                ('audttime', models.DecimalField(db_column='AUDTTIME', decimal_places=0, max_digits=9)),
                ('audtuser', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AUDTUSER', max_length=8)),
                ('audtorg', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AUDTORG', max_length=6)),
                ('docno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DOCNO', max_length=22)),
                ('docdesc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DOCDESC', max_length=60)),
                ('refdocid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='REFDOCID', max_length=22)),
                ('doccate', models.SmallIntegerField(db_column='DOCCATE')),
                ('keywords', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='KEYWORDS', max_length=255)),
                ('docpath', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DOCPATH', max_length=255)),
                ('docname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DOCNAME', max_length=255)),
                ('notes', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NOTES', max_length=255)),
                ('employeid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EMPLOYEID', max_length=16)),
                ('lstmntdt', models.DecimalField(db_column='LSTMNTDT', decimal_places=0, max_digits=9)),
                ('lstmntby', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LSTMNTBY', max_length=16)),
                ('fileid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FILEID', max_length=36)),
                ('reqid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='REQID', max_length=36)),
                ('cntline', models.IntegerField(db_column='CNTLINE')),
            ],
            options={
                'db_table': 'ENEBA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enpjd',
            fields=[
                ('typebtch', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TYPEBTCH', max_length=2, primary_key=True, serialize=False)),
                ('postseqnce', models.DecimalField(db_column='POSTSEQNCE', decimal_places=0, max_digits=9)),
                ('cntbtch', models.DecimalField(db_column='CNTBTCH', decimal_places=0, max_digits=9)),
                ('cntitem', models.DecimalField(db_column='CNTITEM', decimal_places=0, max_digits=7)),
                ('iddoc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IDDOC', max_length=22)),
                ('fiscy', models.SmallIntegerField(db_column='FISCY')),
                ('fiscperd', models.SmallIntegerField(db_column='FISCPERD')),
                ('cntline', models.DecimalField(db_column='CNTLINE', decimal_places=0, max_digits=7)),
                ('cntseqence', models.IntegerField(db_column='CNTSEQENCE')),
                ('audtdate', models.DecimalField(db_column='AUDTDATE', decimal_places=0, max_digits=9)),
                ('audttime', models.DecimalField(db_column='AUDTTIME', decimal_places=0, max_digits=9)),
                ('audtuser', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AUDTUSER', max_length=8)),
                ('audtorg', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AUDTORG', max_length=6)),
                ('idemp', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IDEMP', max_length=16)),
                ('drcr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DRCR', max_length=2)),
                ('idexpctl', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IDEXPCTL', max_length=45)),
                ('accttype', models.SmallIntegerField(db_column='ACCTTYPE')),
                ('amtextndhc', models.DecimalField(db_column='AMTEXTNDHC', decimal_places=3, max_digits=19)),
                ('amtextndtc', models.DecimalField(db_column='AMTEXTNDTC', decimal_places=3, max_digits=19)),
                ('posted', models.SmallIntegerField(db_column='POSTED')),
                ('srcetype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SRCETYPE', max_length=2)),
                ('glref', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLREF', max_length=60)),
                ('gldesc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLDESC', max_length=60)),
                ('glbatnbr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLBATNBR', max_length=6)),
                ('gljrnlid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLJRNLID', max_length=5)),
                ('gltrsnbr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GLTRSNBR', max_length=10)),
                ('notes', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NOTES', max_length=30)),
                ('sourcurr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SOURCURR', max_length=3)),
                ('ratetype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RATETYPE', max_length=2)),
                ('ratedate', models.DecimalField(db_column='RATEDATE', decimal_places=0, max_digits=9)),
                ('rate', models.DecimalField(db_column='RATE', decimal_places=7, max_digits=15)),
                ('values', models.IntegerField(db_column='VALUES')),
                ('datebus', models.DecimalField(db_column='DATEBUS', decimal_places=0, max_digits=9)),
                ('lstmntby', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LSTMNTBY', max_length=8)),
                ('comments', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='COMMENTS', max_length=250)),
                ('dratespren', models.DecimalField(db_column='DRATESPREN', decimal_places=7, max_digits=15)),
                ('dratemtchc', models.SmallIntegerField(db_column='DRATEMTCHC')),
                ('drateoper', models.SmallIntegerField(db_column='DRATEOPER')),
                ('entryseq', models.IntegerField(db_column='ENTRYSEQ')),
            ],
            options={
                'db_table': 'ENPJD',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='iddoc',
            field=models.CharField(default='EV002703                                                    ', max_length=60),
        ),
        migrations.AddField(
            model_name='supportingdocumentfile',
            name='source',
            field=models.CharField(default='System Upload', max_length=50),
        ),
    ]
