# Generated by Django 5.0.14 on 2025-06-23 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_eneba_enpjd_supportingdocument_iddoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocumentfile',
            name='document',
            field=models.FileField(max_length=255, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'png'])]),
        ),
    ]
