# Generated by Django 5.0.14 on 2025-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_supportingdocumentfile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='source',
            field=models.CharField(default='System Upload', max_length=50),
        ),
    ]
