# Generated by Django 5.0.14 on 2025-06-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_fiscalperiodfilter'),
        ('transactions', '0005_comments_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
    ]
