# Generated by Django 5.2 on 2025-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('supported_transactions_number', models.IntegerField()),
                ('supported_transactions_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unsupported_transactions_number', models.IntegerField()),
                ('unsupported_transactions_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
