# Generated by Django 5.0.14 on 2025-06-11 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_syncmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supported_transactions_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supported_transactions_value',
        ),
        migrations.RemoveField(
            model_name='project',
            name='unsupported_transactions_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='unsupported_transactions_value',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FiscalPeriodFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(blank=True, max_length=4, null=True)),
                ('fiscal_period_start', models.CharField(blank=True, max_length=2, null=True)),
                ('fiscal_period_end', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
            options={
                'db_table': 'fiscal_period_filters',
            },
        ),
        migrations.CreateModel(
            name='ProjectPeriodStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=4)),
                ('fiscal_period', models.CharField(max_length=2)),
                ('supported_transactions_number', models.IntegerField(default=0)),
                ('supported_transactions_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unsupported_transactions_number', models.IntegerField(default=0)),
                ('unsupported_transactions_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['fiscal_year', 'fiscal_period'], name='main_app_pr_fiscal__460b54_idx')],
                'unique_together': {('project', 'fiscal_year', 'fiscal_period')},
            },
        ),
    ]
