# Generated by Django 5.0.14 on 2025-06-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_project_supported_transactions_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiscalPeriodFilter',
        ),
    ]
